### ISSUE TITLE
A new exception trace !!!

### ISSUE THREAD

**Issue by papm-sc** [SchwarzIT/spectral-intellij-plugin#27]
**Description:**

-> Please provide a detailed description of your issue and a way to reproduce it

**Stacktraces:**

```
java.lang.RuntimeException: com.schwarzit.spectralIntellijPlugin.exceptions.SpectralException: Unable to unpack spectral binary to: <a href= "C:\Users\patrick.clement\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\221.5787.36.plugins\spectral-intellij-plugin\spectralExecutables\spectral-windows.exe">C:\Users\patrick.clement\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\221.5787.36.plugins\spectral-intellij-plugin\spectralExecutables\spectral-windows.exe</a>
	at com.schwarzit.spectralIntellijPlugin.SpectralStartupAction.runActivity(SpectralStartupAction.java:23)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runStartupActivity(StartupManagerImpl.kt:311)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration(StartupManagerImpl.kt:290)
	at com.intellij.ide.startup.impl.StartupManagerImpl.runActivityAndMeasureDuration$default(StartupManagerImpl.kt:285)
	at com.intellij.ide.startup.impl.StartupManagerImpl$runPostStartupActivities$1$2.run(StartupManagerImpl.kt:249)
	at com.intellij.codeWithMe.ClientId$Companion$decorateRunnable$1.run(ClientId.kt:278)
	at com.intellij.openapi.project.DumbServiceImpl.doRun(DumbServiceImpl.java:398)
	at com.intellij.openapi.project.DumbServiceImpl.updateFinished(DumbServiceImpl.java:390)
	at com.intellij.openapi.project.TrackedEdtActivityService$TrackedEdtActivity.run(TrackedEdtActivityService.java:66)
	at com.intellij.openapi.application.TransactionGuardImpl.runWithWritingAllowed(TransactionGuardImpl.java:215)
	at com.intellij.openapi.application.TransactionGuardImpl.access$100(TransactionGuardImpl.java:22)
	at com.intellij.openapi.application.TransactionGuardImpl$1.run(TransactionGuardImpl.java:197)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.openapi.application.impl.ApplicationImpl$3.run(ApplicationImpl.java:511)
	at com.intellij.openapi.application.impl.FlushQueue.doRun(FlushQueue.java:69)
	at com.intellij.openapi.application.impl.FlushQueue.runNextEvent(FlushQueue.java:112)
	at com.intellij.openapi.application.impl.FlushQueue.flushNow(FlushQueue.java:42)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:313)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:776)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:898)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:746)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$6(IdeEventQueue.java:439)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:803)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$7(IdeEventQueue.java:438)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueue.performActivity(IdeEventQueue.java:604)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:436)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:873)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:484)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: com.schwarzit.spectralIntellijPlugin.exceptions.SpectralException: Unable to unpack spectral binary to: <a href= "C:\Users\patrick.clement\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\221.5787.36.plugins\spectral-intellij-plugin\spectralExecutables\spectral-windows.exe">C:\Users\patrick.clement\AppData\Local\JetBrains\Toolbox\apps\Rider\ch-0\221.5787.36.plugins\spectral-intellij-plugin\spectralExecutables\spectral-windows.exe</a>
	at com.schwarzit.spectralIntellijPlugin.StorageManager.installSpectralBinary(StorageManager.java:69)
	at com.schwarzit.spectralIntellijPlugin.SpectralStartupAction.runActivity(SpectralStartupAction.java:20)
	... 39 more

```

**Comment by markbrockhoff** [comment]
Hi, thanks for your report, sorry for the delayed answer. We just released a new major version of the plugin. I'm closing this issue as it should be resolved with the new version.
Please feel free to try it out.
Please note, that we decided to no longer bundle the Spectral CLI within the plugin, so you'll have to install it on your system yourself.
